global:
  scrape_interval: 5s
  external_labels:
    monitor: 'example-monitoring'

scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['prometheus:9090']

  - job_name: 'example-application' 
    metrics_path: /metrics
    static_configs: 
      - targets: ['application:8000']
